/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  DeterministicFactory,
  DeterministicFactoryInterface,
} from "../../contracts/DeterministicFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "bytecode",
        type: "bytes",
      },
    ],
    name: "deploy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "bytecode",
        type: "bytes",
      },
    ],
    name: "getDeploymentAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061026a806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806309b1eca61461003b578063cdcb760a146100f9575b600080fd5b6100d061004936600461015b565b8051602091820120604080517fff00000000000000000000000000000000000000000000000000000000000000818501523060601b7fffffffffffffffffffffffffffffffffffffffff0000000000000000000000001660218201526035810194909452605580850192909252805180850390920182526075909301909252815191012090565b60405173ffffffffffffffffffffffffffffffffffffffff909116815260200160405180910390f35b61010c61010736600461015b565b61010e565b005b6000828251602084016000f59050803b61012757600080fd5b505050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b6000806040838503121561016e57600080fd5b82359150602083013567ffffffffffffffff8082111561018d57600080fd5b818501915085601f8301126101a157600080fd5b8135818111156101b3576101b361012c565b604051601f82017fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe0908116603f011681019083821181831017156101f9576101f961012c565b8160405282815288602084870101111561021257600080fd5b826020860160208301376000602084830101528095505050505050925092905056fea26469706673582212204b544c38d50f782e25a8ce9b70e74a99700873873c076318ced09215e02cf75064736f6c63430008110033";

type DeterministicFactoryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DeterministicFactoryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DeterministicFactory__factory extends ContractFactory {
  constructor(...args: DeterministicFactoryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DeterministicFactory & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): DeterministicFactory__factory {
    return super.connect(runner) as DeterministicFactory__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DeterministicFactoryInterface {
    return new Interface(_abi) as DeterministicFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DeterministicFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as DeterministicFactory;
  }
}
